# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hl999_finalProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hl999_finalProject
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'SwiftyJSON'

end
